[project]
name = "neural-networks"
version = "0.1.0"
authors = [ {name = "Silas Henrique", email = "silash35@gmail.com"}, ]
requires-python = "==3.14.0"
dependencies = ["scipy-dae>=0.1.0,<0.2"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
assimulo = ">=3.7.2,<4"
matplotlib = ">=3.10.7,<4"
ipykernel = ">=7.0.1,<8"
scipy = ">=1.16.3,<2"
pandas = ">=2.3.3,<3"
ruff = ">=0.14.2,<0.15"
casadi = ">=3.7.0,<4"

[tool.ruff.lint]
extend-select = ["I"]
